services:
  - docker

before_install:
  - docker build -t rcsillag/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rcsillag/react-test npm test

after_success:
  - docker build -t rcsillag/fibonacci-calc-client ./client
  - docker build -t rcsillag/fibonacci-calc-nginx ./nginx
  - docker build -t rcsillag/fibonacci-calc-server ./server
  - docker build -t rcsillag/fibonacci-calc-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to dockerhub
  - docker push rcsillag/fibonacci-calc-client
  - docker push rcsillag/fibonacci-calc-nginx
  - docker push rcsillag/fibonacci-calc-server
  - docker push rcsillag/fibonacci-calc-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-458875892965'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY